openapi: 3.0.3

info:
  title: Customers API
  description: API for managing customers
  version: 1.0.0

paths:
  /customer:
    post:
      summary: Create a customer
      description: Creates a customer
      operationId: createCustomer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CustomerCreateRequest'
      responses:
        '201':
          description: Customer created correctly.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Customer'
        '409':
          description: Customer email already exists.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomerErrorDuplicateEmail'
  /customer/{id}:
    get:
      summary: Obtain a customer by ID
      description: Retrieves a customer by ID
      operationId: getCustomerById
      parameters:
        - name: id
          in: path
          description: Identifier of customer
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Customer obtained correctly.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Customer'
        '404':
          description: Customer not found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomerErrorNotFound'

    patch:
      summary: Modify a customer
      description: Modifies a customer
      operationId: modifyCustomer
      parameters:
        - name: id
          in: path
          description: Identifier of customer
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CustomerUpdateRequest'
      responses:
        '200':
          description: Customer updated correctly.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Customer'
        '404':
          description: Customer not found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomerErrorNotFound'
        '409':
          description: Customer email already exists.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomerErrorDuplicateEmail'
    delete:
      summary: Delete a customer by ID
      description: Deletes a customer by ID
      operationId: deleteCustomerById
      parameters:
        - name: id
          in: path
          description: Identifier of customer
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Customer deleted correctly.
        '404':
          description: Customer not found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomerErrorNotFound'

components:
  schemas:
    Customer:
      type: object
      required:
        - id
        - name
        - surname
        - email
      properties:
        id:
          type: integer
          example: 42
        name:
          type: string
          example: "María"
        surname:
          type: string
          example: "Garcia"
        email:
          type: string
          format: email
          example: "maria.garcia@ejemplo.com"
    CustomerCreateRequest:
      type: object
      required:
        - name
        - surname
        - email
      properties:
        name:
          type: string
          example: "María"
        surname:
          type: string
          example: "Garcia"
        email:
          type: string
          format: email
          example: "maria.garcia@ejemplo.com"
    CustomerErrorNotFound:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: string
          description: Internal error.
          example: "CUSTOMER_DOES_NOT_EXIST"
        message:
          type: string
          description: Error description
          example: "Customer does not exist."
    CustomerErrorDuplicateEmail:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: string
          description: Error code.
          example: "CUSTOMER_ERROR_DUPLICATE_EMAIL"
        message:
          type: string
          description: Error description
          example: "We can not create a customer with an existing email"
    CustomerUpdateRequest:
      type: object
      properties:
        name:
          type: string
          example: "María"
        surname:
          type: string
          example: "Garcia"
        email:
          type: string
          format: email
          example: "maria.garcia@ejemplo.com"